// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhi1LkDkgskddCRJ-Or3iceYZxIPxRFms',
    appId: '1:214487377463:android:037f2993153e5ad3d1c1b2',
    messagingSenderId: '214487377463',
    projectId: 'birdie-app-ab3c6',
    databaseURL: 'https://birdie-app-ab3c6-default-rtdb.firebaseio.com',
    storageBucket: 'birdie-app-ab3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKH2Bv5fX8ddijzGcFR0si5vpINN0s18',
    appId: '1:214487377463:ios:0c1fa62e63b25c36d1c1b2',
    messagingSenderId: '214487377463',
    projectId: 'birdie-app-ab3c6',
    databaseURL: 'https://birdie-app-ab3c6-default-rtdb.firebaseio.com',
    storageBucket: 'birdie-app-ab3c6.appspot.com',
    androidClientId: '214487377463-73onv6mus0kuq9ec12isie6uhhnju2ee.apps.googleusercontent.com',
    iosClientId: '214487377463-6dbjbathr8aebtmnj90t0673oqneqqg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJGoZN2JCRQ2rz9EH2dF49KUw6FIakjg',
    appId: '1:214487377463:web:303fa4ffc3540f05d1c1b2',
    messagingSenderId: '214487377463',
    projectId: 'birdie-app-ab3c6',
    authDomain: 'birdie-app-ab3c6.firebaseapp.com',
    databaseURL: 'https://birdie-app-ab3c6-default-rtdb.firebaseio.com',
    storageBucket: 'birdie-app-ab3c6.appspot.com',
    measurementId: 'G-0WMNC1J3JN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUKH2Bv5fX8ddijzGcFR0si5vpINN0s18',
    appId: '1:214487377463:ios:0c1fa62e63b25c36d1c1b2',
    messagingSenderId: '214487377463',
    projectId: 'birdie-app-ab3c6',
    databaseURL: 'https://birdie-app-ab3c6-default-rtdb.firebaseio.com',
    storageBucket: 'birdie-app-ab3c6.appspot.com',
    androidClientId: '214487377463-73onv6mus0kuq9ec12isie6uhhnju2ee.apps.googleusercontent.com',
    iosClientId: '214487377463-6dbjbathr8aebtmnj90t0673oqneqqg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxJGoZN2JCRQ2rz9EH2dF49KUw6FIakjg',
    appId: '1:214487377463:web:2de279fad40c4871d1c1b2',
    messagingSenderId: '214487377463',
    projectId: 'birdie-app-ab3c6',
    authDomain: 'birdie-app-ab3c6.firebaseapp.com',
    databaseURL: 'https://birdie-app-ab3c6-default-rtdb.firebaseio.com',
    storageBucket: 'birdie-app-ab3c6.appspot.com',
    measurementId: 'G-6VHQE6N7QH',
  );

}